# Generated by Django 4.1.7 on 2023-05-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormModel',
        ),
    ]
