# Generated by Django 4.1.7 on 2023-05-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_form_formmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormModel',
            new_name='Doctor',
        ),
    ]
